"""Wiki tools — search, read, list wiki pages for the AI agent."""

import json

from fava_ai.knowledge.wiki import WikiManager
from fava_ai.tools.base import BaseTool, ToolResult

#: Directories / files regenerated by the knowledge-base extractors. The agent
#: must not silently overwrite them.
RESERVED_WIKI_PREFIXES = (
    "accounts/",
    "merchants/",
    "recurring/",
    "portfolio/",
    "patterns/",
)
RESERVED_WIKI_FILES = {"overview.md", "index.md", "AGENTS.md", "log.md"}


class WikiSearchTool(BaseTool):
    def __init__(self, wiki: WikiManager):
        self._wiki = wiki

    @property
    def name(self) -> str:
        return "wiki_search"

    @property
    def description(self) -> str:
        return "Search the knowledge base wiki pages by keyword. Returns matching page paths with titles and snippets."

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Search query string",
                },
            },
            "required": ["query"],
        }

    def execute(self, query: str) -> ToolResult:
        results = self._wiki.search(query)
        return ToolResult(
            content=json.dumps(results, indent=2, ensure_ascii=False),
            metadata={"query": query, "count": len(results)},
        )


class WikiReadTool(BaseTool):
    def __init__(self, wiki: WikiManager):
        self._wiki = wiki

    @property
    def name(self) -> str:
        return "wiki_read"

    @property
    def description(self) -> str:
        return "Read a specific wiki page by its relative path (e.g. 'accounts/Expenses-Food.md' or 'overview.md')."

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": "Relative path to the wiki page",
                },
            },
            "required": ["path"],
        }

    def execute(self, path: str) -> ToolResult:
        if not self._wiki.exists(path):
            return ToolResult(
                content=json.dumps({"error": f"Page not found: {path}"}),
                metadata={"path": path, "found": False, "error": f"Page not found: {path}"},
            )
        page = self._wiki.read(path)
        return ToolResult(
            content=page.to_text(),
            metadata={"path": path, "title": page.metadata.get("title", ""), "type": page.metadata.get("type", "")},
        )


class WikiListTool(BaseTool):
    def __init__(self, wiki: WikiManager):
        self._wiki = wiki

    @property
    def name(self) -> str:
        return "wiki_list"

    @property
    def description(self) -> str:
        return "List wiki pages, optionally filtered by type prefix (e.g. 'accounts', 'merchants', 'recurring')."

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "Optional directory prefix to filter (e.g. 'accounts', 'merchants')",
                },
            },
        }

    def execute(self, prefix: str = "") -> ToolResult:
        pages = self._wiki.list_pages(prefix)
        return ToolResult(
            content=json.dumps(pages, indent=2, ensure_ascii=False),
            metadata={"prefix": prefix, "count": len(pages)},
        )


class WikiWriteTool(BaseTool):
    def __init__(self, wiki: WikiManager):
        self._wiki = wiki

    @property
    def name(self) -> str:
        return "wiki_write"

    @property
    def description(self) -> str:
        return (
            "Create or update a wiki note. Path is relative to the wiki root "
            "(e.g. 'notes/tax_2024.md'). Auto-generated pages (accounts/, "
            "merchants/, recurring/, portfolio/, patterns/, overview.md, "
            "index.md, log.md, AGENTS.md) cannot be overwritten unless "
            "overwrite=true is set."
        )

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": "Relative path for the wiki page (e.g. 'notes/budget.md')",
                },
                "content": {
                    "type": "string",
                    "description": "Markdown content for the page",
                },
                "title": {
                    "type": "string",
                    "description": "Page title for frontmatter metadata",
                },
                "overwrite": {
                    "type": "boolean",
                    "description": "Allow overwriting auto-generated pages (default false)",
                },
            },
            "required": ["path", "content"],
        }

    @property
    def permission(self) -> str:
        return "write"

    @staticmethod
    def _is_reserved(rel_path: str) -> bool:
        normalized = rel_path.lstrip("/")
        name = normalized.rsplit("/", 1)[-1]
        if name in RESERVED_WIKI_FILES:
            return True
        return any(normalized.startswith(prefix) for prefix in RESERVED_WIKI_PREFIXES)

    def execute(self, path: str, content: str, title: str = "", overwrite: bool = False) -> ToolResult:
        if not overwrite and self._is_reserved(path):
            message = (
                f"Refusing to overwrite auto-generated wiki page '{path}'. "
                "Choose a different path (e.g. under notes/) or pass overwrite=true."
            )
            return ToolResult(
                content=json.dumps({"error": message}),
                metadata={"path": path, "error": message},
            )

        metadata = {"title": title or path, "type": "note"}
        try:
            self._wiki.write(path, content, metadata)
            return ToolResult(
                content=f"Wiki page written: {path}",
                metadata={"path": path, "title": title},
            )
        except ValueError as e:
            return ToolResult(
                content=f"Error writing wiki page: {e}",
                metadata={"error": str(e), "path": path},
            )


def register_wiki_tools(registry, wiki: WikiManager):
    registry.register(WikiSearchTool(wiki))
    registry.register(WikiReadTool(wiki))
    registry.register(WikiListTool(wiki))
    registry.register(WikiWriteTool(wiki))
